"""Export every sensor rig into .docs/figures (PNG, HTML, GLB, tree).

Usage::

    uv run python lidar_bedlam/scripts/export_rigs.py            # all rigs
    uv run python lidar_bedlam/scripts/export_rigs.py waymo ava  # a subset

Writes ``.docs/figures/rigs/<slug>.{png,html,glb,txt}`` plus the
note ``.docs/figures/rigs.md`` that embeds them. The GLB files open
in Obsidian with a 3D-model viewer community plugin (glTF support) and in
any glTF viewer; the HTML files open in a browser and need the
``plotly.min.js`` written next to them.
"""

from __future__ import annotations

import sys
from pathlib import Path

from lidar_bedlam.rigs.export import export_rig
from lidar_bedlam.rigs.registry import load_all_rigs

VAULT = Path(".docs/figures")
OUT = VAULT / "rigs"
NOTE = VAULT / "rigs.md"


def note_text(entries: list[tuple[str, str, str]]) -> str:
    """Markdown note embedding the files; entries = (slug, title, tree)."""
    lines = [
        "# Sensor rigs (calibration trees)",
        "",
        "Generated by `lidar_bedlam/scripts/export_rigs.py` from the",
        "datasets' own",
        "calibration files. Axes: x red, y green, z blue; grey dotted links",
        "to the base link; orange camera frustums from the intrinsics.",
        "Each rig has a static PNG, an interactive HTML (open in a browser;",
        "needs `rigs/plotly.min.js`) and a GLB 3D model (Obsidian: install a",
        "3D-model viewer plugin with glTF support, then embed it like an",
        "image).",
        "",
    ]
    for slug, title, tree in entries:
        lines += [
            f"## {title}",
            "",
            f"![[rigs/{slug}.png]]",
            "",
            f"- interactive: [[rigs/{slug}.html]]",
            f"- 3D model: ![[rigs/{slug}.glb]]",
            "",
            "```",
            tree.rstrip(),
            "```",
            "",
        ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """CLI."""
    wanted = set(sys.argv[1:] if argv is None else argv)
    rigs, skipped = load_all_rigs(Path("resources/data"))
    for slug, why in skipped.items():
        sys.stderr.write(f"skipped {slug}: {why}\n")
    entries: list[tuple[str, str, str]] = []
    for slug, rig in rigs.items():
        if wanted and slug not in wanted:
            continue
        files = export_rig(rig, OUT, slug)
        entries.append((slug, rig.title, rig.tree_text()))
        sys.stdout.write(
            f"{slug}: {', '.join(p.name for p in files.values())}\n"
        )
    NOTE.write_text(note_text(entries), encoding="utf-8")
    sys.stdout.write(f"wrote {NOTE}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
